---
title: "HAandAvg"
author: "Matthias Lochmann"
format: revealjs
editor: visual
bibliography: references.bib
---

## Daten einlesen

Die Daten von der [Datenveröffentlichung](https://doi.org/10.5281/zenodo.15172913) werden hier als Dataframe eingelesen

```{r}
#| label: read_data
library(tidyverse)
library(scales)
data <- read_delim(
  "SchaefferEtAl_NORAH_DataSet_V1_2025-05.csv",
  delim = ";",
  escape_double = FALSE,
  trim_ws = TRUE
)

summary(data)
```

## Belästigungs-Kurven LDEN

```{r}
#| label: HAkurven
plotFra <- function(dat) {
  dat %>%
    filter(AirportName == "FRA") %>%
    group_by(
      Year,
      #subStudie,
      pegel
    ) %>%
    summarise(n = n(), HA = mean(HAv_air)) %>%
    ggplot(aes(
      x = pegel,
      HA,
      #color=factor(subStudie),
      color = factor(Year)
    )) +
    scale_y_continuous(labels = percent_format(accuracy = 1),
                       breaks=seq(0,1,.1))+
    geom_line() +
    geom_point(aes(size = n))
    #facet_wrap(vars(Year))
}

data %>%
  mutate(pegel = round(Air_LDEN),
         subStudie = as.character(compstudie2)) %>%
  plotFra()+
  labs(title = "Fluglärmbelästigung am Frankfurter Flughafen (abhängig von LDEN)",
       x="LDEN")

```

## Umrechnung auf LD

Gemäß [@brink2018] ist für Flugverkehr

$$L_{\textrm{D}}=L_{\textrm{DEN}}-2,3\,\textrm{dB}.$$

## Verschobene HA-Kurve

Angewandt auf obigen Datensatz verschiebt sich die x-Achse:

```{r}
data %>%
  mutate(pegel = round(Air_LDEN-2.3),
         subStudie = as.character(compstudie2)) %>%
  plotFra()+
  labs(title = "Fluglärmbelästigung am Frankfurter Flughafen (abhängig von LD)",
       x="LD")
```

## Literatur
